spring:
  data:
    mongodb:
      host: localhost
      port: 27020
      database: links
      username: mongouserrw
      password: secret
      authentication-database: admin
logging:
  level:
    root: INFO